import type { MeshInfo } from "../types";

export function normalizeObj(objText: string): string {
  const vertices: string[] = [];
  const faces: string[] = [];

  for (const line of objText.split("\n")) {
    const trimmed = line.trim();
    if (trimmed.startsWith("v ")) {
      vertices.push(trimmed);
    } else if (trimmed.startsWith("f ")) {
      faces.push(trimmed.replace(/\/\/\d+/g, ""));
    }
  }

  return [
    "# Generated by rocktools-wasm",
    "o tri_mesh",
    ...vertices,
    ...faces,
    "",
  ].join("\n");
}

export function parseMeshInfoFromObj(objText: string): MeshInfo {
  let vCount = 0;
  let fCount = 0;
  const min = [Infinity, Infinity, Infinity];
  const max = [-Infinity, -Infinity, -Infinity];

  for (const line of objText.split("\n")) {
    if (line.startsWith("v ")) {
      vCount++;
      const parts = line.trim().split(/\s+/);
      for (let i = 0; i < 3; i++) {
        const val = parseFloat(parts[i + 1]!);
        if (val < min[i]!) min[i] = val;
        if (val > max[i]!) max[i] = val;
      }
    } else if (line.startsWith("f ")) {
      fCount++;
    }
  }

  return {
    nodes: vCount,
    tris: fCount,
    bounds: {
      x: [min[0]!, max[0]!],
      y: [min[1]!, max[1]!],
      z: [min[2]!, max[2]!],
    },
  };
}

export function parseMeshInfo(text: string): MeshInfo {
  const nodesMatch = text.match(/nodes\s+(\d+)/);
  const trisMatch = text.match(/tris\s+(\d+)/);
  const xMatch = text.match(/x\s+([^\s]+)\s+([^\s]+)/);
  const yMatch = text.match(/y\s+([^\s]+)\s+([^\s]+)/);
  const zMatch = text.match(/z\s+([^\s]+)\s+([^\s]+)/);

  return {
    nodes: nodesMatch ? parseInt(nodesMatch[1]!, 10) : 0,
    tris: trisMatch ? parseInt(trisMatch[1]!, 10) : 0,
    bounds: {
      x: [parseFloat(xMatch?.[1] ?? "0"), parseFloat(xMatch?.[2] ?? "0")],
      y: [parseFloat(yMatch?.[1] ?? "0"), parseFloat(yMatch?.[2] ?? "0")],
      z: [parseFloat(zMatch?.[1] ?? "0"), parseFloat(zMatch?.[2] ?? "0")],
    },
  };
}
