import { mulberry32 } from "./prng";

export interface MeshData {
  positions: Float64Array;
  normals: Float64Array;
  indices: Uint32Array;
  vertexCount: number;
  triCount: number;
  occupancy?: Float64Array;
  featureData?: Float32Array;
  featureData2?: Float32Array;
}

export interface MeshModifier {
  name: string;
  apply(mesh: MeshData, params: Record<string, number | string | boolean>): MeshData;
}

export function ensureOccupancy(mesh: MeshData): Float64Array {
  if (!mesh.occupancy) mesh.occupancy = new Float64Array(mesh.vertexCount);
  return mesh.occupancy;
}

export function ensureFeatureData(mesh: MeshData): Float32Array {
  if (!mesh.featureData) mesh.featureData = new Float32Array(mesh.vertexCount * 4);
  return mesh.featureData;
}

export function ensureFeatureData2(mesh: MeshData): Float32Array {
  if (!mesh.featureData2) mesh.featureData2 = new Float32Array(mesh.vertexCount * 4);
  return mesh.featureData2;
}

export function buildAdjacency(indices: Uint32Array, vertexCount: number): number[][] {
  const adj: Set<number>[] = Array.from({ length: vertexCount }, () => new Set());
  for (let i = 0; i < indices.length; i += 3) {
    const a = indices[i]!, b = indices[i + 1]!, c = indices[i + 2]!;
    adj[a]!.add(b); adj[a]!.add(c);
    adj[b]!.add(a); adj[b]!.add(c);
    adj[c]!.add(a); adj[c]!.add(b);
  }
  return adj.map(s => [...s]);
}

export function parseOBJToMeshData(objText: string): MeshData {
  const vPositions: number[] = [];
  const faces: number[] = [];

  const lines = objText.split("\n");
  for (const line of lines) {
    const parts = line.trim().split(/\s+/);
    if (parts[0] === "v" && parts.length >= 4) {
      vPositions.push(parseFloat(parts[1]!), parseFloat(parts[2]!), parseFloat(parts[3]!));
    } else if (parts[0] === "f") {
      const faceVerts: number[] = [];
      for (let i = 1; i < parts.length; i++) {
        const idx = parseInt(parts[i]!.split("/")[0]!) - 1;
        if (idx >= 0) faceVerts.push(idx);
      }
      for (let i = 1; i < faceVerts.length - 1; i++) {
        faces.push(faceVerts[0]!, faceVerts[i]!, faceVerts[i + 1]!);
      }
    }
  }

  const vertexCount = vPositions.length / 3;
  const positions = new Float64Array(vPositions);
  const indices = new Uint32Array(faces);
  const normals = computeVertexNormals(positions, indices, vertexCount);

  return { positions, normals, indices, vertexCount, triCount: faces.length / 3 };
}

export function computeVertexNormals(
  positions: Float64Array,
  indices: Uint32Array,
  vertexCount: number,
): Float64Array {
  const normals = new Float64Array(vertexCount * 3);

  for (let i = 0; i < indices.length; i += 3) {
    const i0 = indices[i]!, i1 = indices[i + 1]!, i2 = indices[i + 2]!;
    const ax = positions[i0 * 3]!, ay = positions[i0 * 3 + 1]!, az = positions[i0 * 3 + 2]!;
    const bx = positions[i1 * 3]!, by = positions[i1 * 3 + 1]!, bz = positions[i1 * 3 + 2]!;
    const cx = positions[i2 * 3]!, cy = positions[i2 * 3 + 1]!, cz = positions[i2 * 3 + 2]!;

    const e1x = bx - ax, e1y = by - ay, e1z = bz - az;
    const e2x = cx - ax, e2y = cy - ay, e2z = cz - az;
    const nx = e1y * e2z - e1z * e2y;
    const ny = e1z * e2x - e1x * e2z;
    const nz = e1x * e2y - e1y * e2x;

    normals[i0 * 3] += nx; normals[i0 * 3 + 1] += ny; normals[i0 * 3 + 2] += nz;
    normals[i1 * 3] += nx; normals[i1 * 3 + 1] += ny; normals[i1 * 3 + 2] += nz;
    normals[i2 * 3] += nx; normals[i2 * 3 + 1] += ny; normals[i2 * 3 + 2] += nz;
  }

  for (let i = 0; i < vertexCount; i++) {
    const x = normals[i * 3]!, y = normals[i * 3 + 1]!, z = normals[i * 3 + 2]!;
    const len = Math.sqrt(x * x + y * y + z * z);
    if (len > 1e-10) {
      normals[i * 3] /= len;
      normals[i * 3 + 1] /= len;
      normals[i * 3 + 2] /= len;
    }
  }

  return normals;
}

export function meshDataToOBJ(mesh: MeshData): string {
  const lines: string[] = ["# Generated by rocktools"];
  for (let i = 0; i < mesh.vertexCount; i++) {
    lines.push(`v ${mesh.positions[i * 3]} ${mesh.positions[i * 3 + 1]} ${mesh.positions[i * 3 + 2]}`);
  }
  for (let i = 0; i < mesh.triCount; i++) {
    lines.push(`f ${mesh.indices[i * 3]! + 1} ${mesh.indices[i * 3 + 1]! + 1} ${mesh.indices[i * 3 + 2]! + 1}`);
  }
  return lines.join("\n") + "\n";
}

export function computeTriangleAreas(mesh: MeshData): Float64Array {
  const areas = new Float64Array(mesh.triCount);
  for (let i = 0; i < mesh.triCount; i++) {
    const i0 = mesh.indices[i * 3]!, i1 = mesh.indices[i * 3 + 1]!, i2 = mesh.indices[i * 3 + 2]!;
    const ax = mesh.positions[i0 * 3]!, ay = mesh.positions[i0 * 3 + 1]!, az = mesh.positions[i0 * 3 + 2]!;
    const bx = mesh.positions[i1 * 3]!, by = mesh.positions[i1 * 3 + 1]!, bz = mesh.positions[i1 * 3 + 2]!;
    const cx = mesh.positions[i2 * 3]!, cy = mesh.positions[i2 * 3 + 1]!, cz = mesh.positions[i2 * 3 + 2]!;
    const e1x = bx - ax, e1y = by - ay, e1z = bz - az;
    const e2x = cx - ax, e2y = cy - ay, e2z = cz - az;
    const crossX = e1y * e2z - e1z * e2y;
    const crossY = e1z * e2x - e1x * e2z;
    const crossZ = e1x * e2y - e1y * e2x;
    areas[i] = 0.5 * Math.sqrt(crossX * crossX + crossY * crossY + crossZ * crossZ);
  }
  return areas;
}

export function pickRandomSurfacePoint(
  mesh: MeshData,
  areas: Float64Array,
  totalArea: number,
  rand: () => number,
): { point: [number, number, number]; normal: [number, number, number] } {
  let r = rand() * totalArea;
  let triIdx = 0;
  for (let i = 0; i < areas.length; i++) {
    r -= areas[i]!;
    if (r <= 0) { triIdx = i; break; }
  }

  const i0 = mesh.indices[triIdx * 3]!, i1 = mesh.indices[triIdx * 3 + 1]!, i2 = mesh.indices[triIdx * 3 + 2]!;
  let u = rand(), v = rand();
  if (u + v > 1) { u = 1 - u; v = 1 - v; }
  const w = 1 - u - v;

  const px = w * mesh.positions[i0 * 3]! + u * mesh.positions[i1 * 3]! + v * mesh.positions[i2 * 3]!;
  const py = w * mesh.positions[i0 * 3 + 1]! + u * mesh.positions[i1 * 3 + 1]! + v * mesh.positions[i2 * 3 + 1]!;
  const pz = w * mesh.positions[i0 * 3 + 2]! + u * mesh.positions[i1 * 3 + 2]! + v * mesh.positions[i2 * 3 + 2]!;

  const nx = w * mesh.normals[i0 * 3]! + u * mesh.normals[i1 * 3]! + v * mesh.normals[i2 * 3]!;
  const ny = w * mesh.normals[i0 * 3 + 1]! + u * mesh.normals[i1 * 3 + 1]! + v * mesh.normals[i2 * 3 + 1]!;
  const nz = w * mesh.normals[i0 * 3 + 2]! + u * mesh.normals[i1 * 3 + 2]! + v * mesh.normals[i2 * 3 + 2]!;
  const nLen = Math.sqrt(nx * nx + ny * ny + nz * nz);

  return {
    point: [px, py, pz],
    normal: nLen > 1e-10 ? [nx / nLen, ny / nLen, nz / nLen] : [0, 1, 0],
  };
}

export function getMeshRadius(mesh: MeshData): number {
  let maxR2 = 0;
  for (let i = 0; i < mesh.vertexCount; i++) {
    const x = mesh.positions[i * 3]!, y = mesh.positions[i * 3 + 1]!, z = mesh.positions[i * 3 + 2]!;
    const r2 = x * x + y * y + z * z;
    if (r2 > maxR2) maxR2 = r2;
  }
  return Math.sqrt(maxR2);
}

export function applyMeshModifiers(
  mesh: MeshData,
  modifiers: { modifier: MeshModifier; params: Record<string, number | string | boolean> }[],
): MeshData {
  let result = mesh;
  for (const { modifier, params } of modifiers) {
    result = modifier.apply(result, params);
  }
  return result;
}

export interface MeshValidationResult {
  valid: boolean;
  error?: string;
  stats?: { nanCount: number; infCount: number; degenerateTriCount: number; maxExtent: number };
}

export function validateMesh(mesh: MeshData): MeshValidationResult {
  let nanCount = 0;
  let infCount = 0;
  for (let i = 0; i < mesh.vertexCount * 3; i++) {
    const v = mesh.positions[i]!;
    if (Number.isNaN(v)) nanCount++;
    else if (!Number.isFinite(v)) infCount++;
  }

  if (nanCount > 0 || infCount > 0) {
    return {
      valid: false,
      error: `Mesh contains invalid vertices: ${nanCount} NaN, ${infCount} Infinity`,
      stats: { nanCount, infCount, degenerateTriCount: 0, maxExtent: 0 },
    };
  }

  let minX = Infinity, minY = Infinity, minZ = Infinity;
  let maxX = -Infinity, maxY = -Infinity, maxZ = -Infinity;
  for (let i = 0; i < mesh.vertexCount; i++) {
    const x = mesh.positions[i * 3]!, y = mesh.positions[i * 3 + 1]!, z = mesh.positions[i * 3 + 2]!;
    if (x < minX) minX = x; if (x > maxX) maxX = x;
    if (y < minY) minY = y; if (y > maxY) maxY = y;
    if (z < minZ) minZ = z; if (z > maxZ) maxZ = z;
  }
  const maxExtent = Math.max(maxX - minX, maxY - minY, maxZ - minZ);
  const avgExtent = ((maxX - minX) + (maxY - minY) + (maxZ - minZ)) / 3;

  // Detect mesh "explosion": if one axis is >10x the average, the mesh is torn apart
  if (avgExtent > 0 && maxExtent / avgExtent > 10) {
    return {
      valid: false,
      error: `Mesh appears torn: extreme aspect ratio (${maxExtent.toFixed(1)} vs avg ${avgExtent.toFixed(1)}). Try lower detail depth.`,
      stats: { nanCount: 0, infCount: 0, degenerateTriCount: 0, maxExtent },
    };
  }

  const edgeCounts = new Map<number, number>();
  const vc = mesh.vertexCount;
  for (let i = 0; i < mesh.triCount; i++) {
    const a = mesh.indices[i * 3]!;
    const b = mesh.indices[i * 3 + 1]!;
    const c = mesh.indices[i * 3 + 2]!;
    const e0 = a < b ? a * vc + b : b * vc + a;
    const e1 = b < c ? b * vc + c : c * vc + b;
    const e2 = a < c ? a * vc + c : c * vc + a;
    edgeCounts.set(e0, (edgeCounts.get(e0) ?? 0) + 1);
    edgeCounts.set(e1, (edgeCounts.get(e1) ?? 0) + 1);
    edgeCounts.set(e2, (edgeCounts.get(e2) ?? 0) + 1);
  }
  let boundaryEdges = 0;
  for (const count of edgeCounts.values()) {
    if (count === 1) boundaryEdges++;
  }
  const totalEdges = edgeCounts.size;
  const boundaryRatio = totalEdges > 0 ? boundaryEdges / totalEdges : 0;
  if (boundaryRatio > 0.08) {
    return {
      valid: false,
      error: `Mesh is not closed: ${boundaryEdges} open edges (${Math.round(boundaryRatio * 100)}% boundary). Try different parameters.`,
      stats: { nanCount: 0, infCount: 0, degenerateTriCount: 0, maxExtent },
    };
  }

  // Volume consistency: detect self-intersecting / crumpled meshes
  // Compare signed volume (from centroid) to total absolute volume
  let centX = 0, centY = 0, centZ = 0;
  for (let i = 0; i < mesh.vertexCount; i++) {
    centX += mesh.positions[i * 3]!;
    centY += mesh.positions[i * 3 + 1]!;
    centZ += mesh.positions[i * 3 + 2]!;
  }
  centX /= mesh.vertexCount;
  centY /= mesh.vertexCount;
  centZ /= mesh.vertexCount;

  let signedVol = 0;
  let absVol = 0;
  for (let i = 0; i < mesh.triCount; i++) {
    const i0 = mesh.indices[i * 3]!, i1 = mesh.indices[i * 3 + 1]!, i2 = mesh.indices[i * 3 + 2]!;
    const ax = mesh.positions[i0 * 3]! - centX, ay = mesh.positions[i0 * 3 + 1]! - centY, az = mesh.positions[i0 * 3 + 2]! - centZ;
    const bx = mesh.positions[i1 * 3]! - centX, by = mesh.positions[i1 * 3 + 1]! - centY, bz = mesh.positions[i1 * 3 + 2]! - centZ;
    const cx = mesh.positions[i2 * 3]! - centX, cy = mesh.positions[i2 * 3 + 1]! - centY, cz = mesh.positions[i2 * 3 + 2]! - centZ;
    const det = ax * (by * cz - bz * cy) - ay * (bx * cz - bz * cx) + az * (bx * cy - by * cx);
    signedVol += det;
    absVol += Math.abs(det);
  }
  const volRatio = absVol > 0 ? Math.abs(signedVol) / absVol : 1;
  if (volRatio < 0.25) {
    return {
      valid: false,
      error: `Mesh appears self-intersecting (volume consistency ${Math.round(volRatio * 100)}%). Try different parameters.`,
      stats: { nanCount: 0, infCount: 0, degenerateTriCount: 0, maxExtent },
    };
  }

  let degenerateTriCount = 0;
  for (let i = 0; i < mesh.triCount; i++) {
    const i0 = mesh.indices[i * 3]!, i1 = mesh.indices[i * 3 + 1]!, i2 = mesh.indices[i * 3 + 2]!;
    const ax = mesh.positions[i0 * 3]!, ay = mesh.positions[i0 * 3 + 1]!, az = mesh.positions[i0 * 3 + 2]!;
    const bx = mesh.positions[i1 * 3]!, by = mesh.positions[i1 * 3 + 1]!, bz = mesh.positions[i1 * 3 + 2]!;
    const cx = mesh.positions[i2 * 3]!, cy = mesh.positions[i2 * 3 + 1]!, cz = mesh.positions[i2 * 3 + 2]!;
    const e1x = bx - ax, e1y = by - ay, e1z = bz - az;
    const e2x = cx - ax, e2y = cy - ay, e2z = cz - az;
    const crossX = e1y * e2z - e1z * e2y;
    const crossY = e1z * e2x - e1x * e2z;
    const crossZ = e1x * e2y - e1y * e2x;
    const area = Math.sqrt(crossX * crossX + crossY * crossY + crossZ * crossZ);
    if (area < 1e-15) degenerateTriCount++;
  }

  const degenerateRatio = degenerateTriCount / mesh.triCount;
  if (degenerateRatio > 0.1) {
    return {
      valid: false,
      error: `Mesh has ${Math.round(degenerateRatio * 100)}% degenerate triangles (${degenerateTriCount}/${mesh.triCount}). Try lower detail depth.`,
      stats: { nanCount: 0, infCount: 0, degenerateTriCount, maxExtent },
    };
  }

  return { valid: true, stats: { nanCount: 0, infCount: 0, degenerateTriCount, maxExtent } };
}

export { mulberry32 };
